apiVersion: v1
kind: Service
metadata:
  name: llmservice
  namespace: default
spec:
  type: LoadBalancer  
  selector:
    app: llmserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080