apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helmsource
  namespace: flux-system
spec:
  dependsOn:
    - name: install-crds
  interval: 5m0s
  path: ./helm-sources/
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  wait: true
