---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: helmrelease
  interval: 5m0s
  path: ./k8s/nginx
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  wait: true
