apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deploy
  namespace: default
  labels:
    application: apigateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      application: apigateway
  template:
    metadata:
      labels:
        application: apigateway
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: krakend-cfg
          configMap:
            name: krakend-cfg
        - name: keys
          secret:
            secretName: krakendjwt
      containers:
        - name: application
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '1024Mi'
              cpu: '1000m'
          image: devopsfaith/krakend:2.5.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: krakend-cfg
            mountPath: /etc/krakend
          - name: keys
            mountPath: /etc/krakensecrets
 
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: default
  labels:
    application: apigateway
spec:
  type: ClusterIP
  selector:
    application: apigateway
  ports:
    - port: 8080
      targetPort: 8080
