apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- krakend-deployment.yaml
- krakendsecret_sealed.yaml
configMapGenerator:
- name: krakend-cfg
  namespace: default
  files:
  - ./krakend.json
