apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 1m
  chart:
    spec:
      chart: istiod
      version: ">=1.16.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
