apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 10m
  chartRef: 
    kind: OCIRepository
    name: nginx-gateway-fabric
    namespace: flux-system
