apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: sealed-secrets
      version: ">=1.16.0-0"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
